structure(list(url = "https://clone.psi-mis.org/api/evnt?paging=true&totalPages=true&program=Ymn7RO0lkf7&pageSize=50", 
    status_code = 404L, headers = structure(list(server = "nginx", 
        date = "Wed, 12 Jan 2022 13:34:50 GMT", `content-type` = "text/html;charset=utf-8", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=31536000 ; includeSubDomains", 
        `x-frame-options` = "SAMEORIGIN", `content-language` = "en", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", date = "Wed, 12 Jan 2022 13:34:50 GMT", 
            `content-type` = "text/html;charset=utf-8", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "1; mode=block", `strict-transport-security` = "max-age=31536000 ; includeSubDomains", 
            `x-frame-options` = "SAMEORIGIN", `content-language` = "en", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_clone.psi-mis.org", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class=\"line\" /><h3>Apache Tomcat/8.5.50</h3></body></html>"), 
    date = structure(1641994490, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.182837, 
    connect = 0.211822, pretransfer = 1.042059, starttransfer = 1.349282, 
    total = 1.349386)), class = "response")
